### ISSUE TITLE
[BUG] No existing channels. but i have a channel

### ISSUE THREAD

**Issue by mjk-141** [opensearch-project/alerting#1557]
Hi,
First, I create a monitor and try to get notified via the trigger's action, but it says the channel doesn't exist.
![image](https://github.com/opensearch-project/alerting/assets/62141352/7ff8d106-36da-495c-98ed-0f60f362ccc2)
but i have 1 channel.
![image](https://github.com/opensearch-project/alerting/assets/62141352/4e1682e7-9df6-4454-8f1b-5d9eed9bdab8)
So I tried recreating the channel, but it still says it doesn't exist.
and im running in a Docker Compose environment. Below is the docker-compose file I am using:
```
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_container
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    networks:
      - efk_network
    volumes:
      - "./opensearch-data:/usr/share/opensearch/data"
    ports:
      - "9200:9200"
    expose:
      - 9200
    restart: always

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch_dashboard_container
    networks:
      - efk_network
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS="https://opensearch:9200/"'
    restart: always

networks:
  efk_network:
    driver: bridge
```
If I've missed something, please let me know.
Thanks!
